apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extio-learn
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  rules:
    - host: rover.extio.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: extio-learn
                port:
                  number: 8443
