apiVersion: apps/v1
kind: Deployment
metadata:
  name: extio-learn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extio-learn
  template:
    metadata:
      labels:
        app: extio-learn
    spec:
      containers:
        - name: extio-learn
          image: ext-hyd-ct-reg.extio.io:3000/extio-learn:0.0.6-RELEASE
          ports:
            - containerPort: 8443
          env:
            - name: DB_HOST
              value: "192.168.1.99"
            - name: DB_PORT
              value: "54321"
            - name: DB_USER
              value: "az_postgress_user"
            - name: DB_PASS
              value: "NwQsR@404#123"
            - name: DB_NAME
              value: "extio_learn_db"
